/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Ariana Virginia Amaya Natel (ariijackson96@gmail.com)
 */
public class Agenda extends javax.swing.JFrame {
       
    /**
     * Creates new form agenda_electronica
     */
    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        name = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        dni = new javax.swing.JLabel();
        textoName = new javax.swing.JTextField();
        textoLastname = new javax.swing.JTextField();
        textoDNI = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        birthDate = new javax.swing.JLabel();
        textoAddress = new javax.swing.JTextField();
        textoPhone = new javax.swing.JTextField();
        textoBirthDate = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        aceptar = new javax.swing.JButton();
        next = new javax.swing.JButton();
        back = new javax.swing.JButton();
        indice = new javax.swing.JLabel();
        mostrarIndice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Lucida Bright", 2, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 91, 86));
        titulo.setText("Agenda Electronica");

        name.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        name.setText("Nombre: ");

        lastname.setText("Apellido:");

        dni.setText("D.N.I.:");

        textoName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNameActionPerformed(evt);
            }
        });

        address.setText("Dirección:");

        phone.setText("Telefono:");

        birthDate.setText("F. Nacimiento:");

        textoAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoAddressActionPerformed(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        next.setText(">>");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        back.setText("<<");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        indice.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        indice.setForeground(new java.awt.Color(255, 125, 121));
        indice.setText("Indice:");

        mostrarIndice.setEditable(false);
        mostrarIndice.setText("1");
        mostrarIndice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarIndiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(261, 261, 261))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastname)
                            .addComponent(name)
                            .addComponent(dni))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phone)
                            .addComponent(birthDate)
                            .addComponent(address))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(back)
                        .addGap(18, 18, 18)
                        .addComponent(aceptar)
                        .addGap(18, 18, 18)
                        .addComponent(next))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(indice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mostrarIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(textoName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address)
                    .addComponent(textoAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastname)
                    .addComponent(textoLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone)
                    .addComponent(textoPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dni)
                    .addComponent(textoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthDate)
                    .addComponent(textoBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(next)
                    .addComponent(back))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indice)
                    .addComponent(mostrarIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoAddressActionPerformed

    private void textoNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNameActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        
        //Carga de datos
        names[indiceCount] = textoName.getText();
        lastnames[indiceCount] = textoLastname.getText();
        dni_s[indiceCount] = textoDNI.getText();
        address_s[indiceCount] = textoAddress.getText();
        phones[indiceCount] = textoPhone.getText();
        birthDates[indiceCount] = textoBirthDate.getText();
        
    }//GEN-LAST:event_aceptarActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        //Incremento del indice en 1
        indiceCount++;
        
        //Control para no desbordar los arreglos
        if (indiceCount <= 9) {
            
            //Muestra los campos - para ingresar datos
            textoName.setText(names[indiceCount]);
            textoLastname.setText(lastnames[indiceCount]);
            textoDNI.setText(dni_s[indiceCount]);
            textoAddress.setText(address_s[indiceCount]);
            textoPhone.setText(phones[indiceCount]);
            textoBirthDate.setText(birthDates[indiceCount]);
            
            //Muestro el indice en el que estoy parado
            mostrarIndice.setText(Integer.toString(indiceCount+1));
            
        }
        else {
            //En caso de estar por desbordar, descremento en 1
            indiceCount--;
        }
        
    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        //Decremento del indice en 1
        indiceCount--;
        
        //Control para no desbordar los arreglos
        if (indiceCount >= 0) {
            
            //Mostrar los campos - ingresados 
            textoName.setText(names[indiceCount]);
            textoLastname.setText(lastnames[indiceCount]);
            textoDNI.setText(dni_s[indiceCount]);
            textoAddress.setText(address_s[indiceCount]);
            textoPhone.setText(phones[indiceCount]);
            textoBirthDate.setText(birthDates[indiceCount]);
            
            //Muestra el indice en el que estoy parado
            mostrarIndice.setText(Integer.toString(indiceCount+1));
            
        }
        else {
            //En caso de estar por desbordar, incrementa en 1
            indiceCount++;
        }
        
    }//GEN-LAST:event_backActionPerformed

    private void mostrarIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarIndiceActionPerformed
        
    }//GEN-LAST:event_mostrarIndiceActionPerformed

    //Creacion e inicialización de arreglos para guardar los datos
    String names[] = new String[10];
    String lastnames[] = new String[10];
    String dni_s[] = new String[10];
    String address_s[] = new String[10];
    String phones[] = new String[10];
    String birthDates[] = new String[10];
    
    //Contador para indice de arreglos
    int indiceCount = 0;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel address;
    private javax.swing.JButton back;
    private javax.swing.JLabel birthDate;
    private javax.swing.JLabel dni;
    private javax.swing.JLabel indice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lastname;
    private javax.swing.JTextField mostrarIndice;
    private javax.swing.JLabel name;
    private javax.swing.JButton next;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField textoAddress;
    private javax.swing.JTextField textoBirthDate;
    private javax.swing.JTextField textoDNI;
    private javax.swing.JTextField textoLastname;
    private javax.swing.JTextField textoName;
    private javax.swing.JTextField textoPhone;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
